version: '2'

services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
    volumes:
      - mariadb_data:/bitnami/mariadb

  suitecrm:
    image: bitnami/suitecrm:latest
    ports:
      - '8080:8080'
    environment:
      - SUITECRM_USERNAME=admin
      - SUITECRM_PASSWORD=bitnami123
      - SUITECRM_EMAIL=admin@example.com
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
    depends_on:
      - mariadb
    volumes:
      - suitecrm_data:/bitnami/suitecrm

volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
